/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 29 08:49:01 GMT 2016
 */

package airlinetickets;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import airlinetickets.Airlinetickets;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Airlinetickets_ESTest extends Airlinetickets_ESTest_scaffolding {

  /*@Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        Airlinetickets.main(stringArray0);
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = 0;
      Airlinetickets.Num_Of_Seats_Sold = (-295);
      String[] stringArray0 = new String[2];
      stringArray0[0] = "XY@}8X}t*UEVm+zVF1";
      stringArray0[1] = "XY@}8X}t*UEVm+zVF1";
      Airlinetickets.main(stringArray0);
      Airlinetickets airlinetickets0 = new Airlinetickets("XY@}8X}t*UEVm+zVF1", "XY@}8X}t*UEVm+zVF1");
      airlinetickets0.Maximum_Capacity = (-195);
      airlinetickets0.checkResult("XY@}8X}t*UEVm+zVF1", "+o,Kk");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[] stringArray0 = new String[5];
      Airlinetickets.Num_Of_Seats_Sold = (-177);
      Airlinetickets airlinetickets0 = new Airlinetickets("", "< ");
      airlinetickets0.run();
      Airlinetickets.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-177);
      Airlinetickets airlinetickets0 = new Airlinetickets("", "< ");
      airlinetickets0.run();
      airlinetickets0.checkResult("The airline issued ", (String) null);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-177);
      Airlinetickets airlinetickets0 = new Airlinetickets("Bm^Os9'", "j1G<gj?pNM");
      airlinetickets0.go("");
      airlinetickets0.run();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-2679);
      Airlinetickets airlinetickets0 = new Airlinetickets("", "");
      airlinetickets0.go("");
      String[] stringArray0 = new String[10];
      Airlinetickets.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-2679);
      Airlinetickets airlinetickets0 = new Airlinetickets("", "");
      airlinetickets0.go("");
      airlinetickets0.go("");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[] stringArray0 = new String[5];
      Airlinetickets.Num_Of_Seats_Sold = (-150);
      Airlinetickets airlinetickets0 = new Airlinetickets("[(EXcJ(f=Ie_'1>$R<", "j1GH!M");
      airlinetickets0.checkResult(stringArray0[1], "j1GH!M");
      airlinetickets0.run();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-2679);
      Airlinetickets airlinetickets0 = new Airlinetickets("", "");
      airlinetickets0.checkResult("", (String) null);
      String[] stringArray0 = new String[10];
      Airlinetickets.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1720705875);
      Airlinetickets airlinetickets0 = new Airlinetickets("", "");
      airlinetickets0.checkResult("", "t~m");
      airlinetickets0.checkResult("", "x[d#Qw^BoRX[");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = 0;
      Airlinetickets.Num_Of_Seats_Sold = (-295);
      String[] stringArray0 = new String[2];
      stringArray0[0] = "XY@}8X}t*UEVm+zVF1";
      stringArray0[1] = "[(>BV nnW;HRFS8J%]w";
      Airlinetickets airlinetickets0 = new Airlinetickets("[(>BV nnW;HRFS8J%]w", "[(>BV nnW;HRFS8J%]w");
      airlinetickets0.Num_of_tickets_issued = (-295);
      airlinetickets0.Num_of_tickets_issued = 1125;
      // Undeclared exception!
      Airlinetickets.main(stringArray0);
  }*/

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = 0;
      Airlinetickets.Num_Of_Seats_Sold = (-295);
      String[] stringArray0 = new String[2];
      stringArray0[0] = "XY@}8X}t*UEVm+zVF1";
      stringArray0[1] = "[(>BV nnW;HRFS8J%]w";
      Airlinetickets airlinetickets0 = new Airlinetickets("[(>BV nnW;HRFS8J%]w", "[(>BV nnW;HRFS8J%]w");
      airlinetickets0.Num_of_tickets_issued = (-295);
      // Undeclared exception!
      try { 
        Airlinetickets.main(stringArray0);
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("airlinetickets.Airlinetickets", e);
      }
  }

  /*@Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = 0;
      Airlinetickets.Num_Of_Seats_Sold = (-295);
      Airlinetickets airlinetickets0 = new Airlinetickets("[(>BV nnW;HRFS8J%]w", "[(>BV nnW;HRFS8J%]w");
      airlinetickets0.Num_of_tickets_issued = (-295);
      // Undeclared exception!
      try { 
        airlinetickets0.go("-N");
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("airlinetickets.Airlinetickets", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Airlinetickets airlinetickets0 = null;
      try {
        airlinetickets0 = new Airlinetickets((String) null, (String) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Airlinetickets.Num_of_tickets_issued = (-1943);
      Airlinetickets airlinetickets0 = null;
      try {
        airlinetickets0 = new Airlinetickets("", "");
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("airlinetickets.Airlinetickets", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1720705875);
      Airlinetickets airlinetickets0 = new Airlinetickets("", "");
      airlinetickets0.Maximum_Capacity = (-1720705875);
      // Undeclared exception!
      try { 
        airlinetickets0.checkResult("", "x[d#Qw^BoRX[");
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-177);
      Airlinetickets airlinetickets0 = new Airlinetickets("", "< ");
      airlinetickets0.checkResult("The airline issued ", (String) null);
      airlinetickets0.go("");
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-2679);
      Airlinetickets airlinetickets0 = new Airlinetickets("", "");
      airlinetickets0.go("");
      airlinetickets0.checkResult("", (String) null);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Airlinetickets airlinetickets0 = null;
      try {
        airlinetickets0 = new Airlinetickets("little", "little");
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      String[] stringArray0 = new String[2];
      // Undeclared exception!
      try { 
        Airlinetickets.main(stringArray0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String[] stringArray0 = new String[5];
      Airlinetickets.Num_Of_Seats_Sold = (-177);
      Airlinetickets airlinetickets0 = new Airlinetickets("", "< ");
      Airlinetickets.main(stringArray0);
      airlinetickets0.Maximum_Capacity = (-68);
      airlinetickets0.run();
      airlinetickets0.go("");
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-177);
      Airlinetickets airlinetickets0 = new Airlinetickets("", " Seats !!!");
      airlinetickets0.run();
      airlinetickets0.run();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-176);
      Airlinetickets airlinetickets0 = new Airlinetickets("", "< ");
      airlinetickets0.Num_of_tickets_issued = 926;
      // Undeclared exception!
      airlinetickets0.go("");
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Airlinetickets airlinetickets0 = new Airlinetickets("Cd5[eS|^", "lot");
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Airlinetickets airlinetickets0 = null;
      try {
        airlinetickets0 = new Airlinetickets("average", "average");
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }*/
}
