/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 27 10:37:40 GMT 2016
 */

package airlinetickets;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import airlinetickets.Airlinetickets;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Airlinetickets_ESTest extends Airlinetickets_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-3410);
      System.setCurrentTimeMillis(0);
      String[] stringArray0 = new String[3];
      Airlinetickets.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        Airlinetickets.main(stringArray0);
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1875);
      Airlinetickets airlinetickets0 = new Airlinetickets("V';`W", "");
      airlinetickets0.run();
      airlinetickets0.run();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1862);
      String[] stringArray0 = new String[9];
      Airlinetickets airlinetickets0 = new Airlinetickets("V';`W", "");
      airlinetickets0.run();
      Airlinetickets.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1862);
      Airlinetickets airlinetickets0 = new Airlinetickets("V';`W", "");
      airlinetickets0.run();
      airlinetickets0.checkResult("", "No Bug");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1862);
      String[] stringArray0 = new String[9];
      Airlinetickets.main(stringArray0);
      Airlinetickets.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1862);
      String[] stringArray0 = new String[9];
      Airlinetickets.main(stringArray0);
      Airlinetickets airlinetickets0 = new Airlinetickets("V';`W", "");
      airlinetickets0.checkResult("", "No Bug");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-3410);
      Airlinetickets airlinetickets0 = new Airlinetickets("U.RC(USKdJk", "4H,[l#ymyI0?D2#P");
      airlinetickets0.go("");
      airlinetickets0.run();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1862);
      String[] stringArray0 = new String[9];
      Airlinetickets airlinetickets0 = new Airlinetickets("V';`W", "");
      airlinetickets0.go("s");
      Airlinetickets.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1862);
      Airlinetickets airlinetickets0 = new Airlinetickets("V';`W", "");
      airlinetickets0.go("s");
      airlinetickets0.go("");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1875);
      Airlinetickets airlinetickets0 = new Airlinetickets("V';`W", "");
      airlinetickets0.checkResult("]{[Dhv!peo'", "'|0]#fvt");
      airlinetickets0.run();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1862);
      String[] stringArray0 = new String[9];
      Airlinetickets airlinetickets0 = new Airlinetickets("V';`W", "");
      airlinetickets0.checkResult("", "No Bug");
      Airlinetickets.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1862);
      Airlinetickets airlinetickets0 = new Airlinetickets("V';`W", "");
      airlinetickets0.checkResult("", "No Bug");
      airlinetickets0.go("s");
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Airlinetickets airlinetickets0 = null;
      try {
        airlinetickets0 = new Airlinetickets("", "");
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1875);
      Airlinetickets airlinetickets0 = new Airlinetickets("V';`W", "");
      airlinetickets0.Num_of_tickets_issued = 5000;
      // Undeclared exception!
      airlinetickets0.go("s");
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1862);
      Airlinetickets airlinetickets0 = new Airlinetickets("V';`W", "");
      Airlinetickets.Num_of_tickets_issued = (-1862);
      // Undeclared exception!
      try { 
        airlinetickets0.go("");
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("airlinetickets.Airlinetickets", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Airlinetickets airlinetickets0 = null;
      try {
        airlinetickets0 = new Airlinetickets(" seats to be sold.", (String) null);
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Airlinetickets.Num_of_tickets_issued = (-279);
      Airlinetickets airlinetickets0 = null;
      try {
        airlinetickets0 = new Airlinetickets("", "Interleaving");
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("airlinetickets.Airlinetickets", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-3410);
      Airlinetickets airlinetickets0 = new Airlinetickets("U.RC(USKdJk", "4H,[l#ymyI0?D2#P");
      Airlinetickets.Num_Of_Seats_Sold = 1;
      // Undeclared exception!
      try { 
        airlinetickets0.checkResult("", "YL4");
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1862);
      Airlinetickets airlinetickets0 = new Airlinetickets("V';`W", "");
      airlinetickets0.checkResult("", "No Bug");
      airlinetickets0.checkResult("sxO&&p|", "");
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1875);
      String[] stringArray0 = new String[9];
      Airlinetickets.main(stringArray0);
      Airlinetickets airlinetickets0 = new Airlinetickets("V';`W", "");
      airlinetickets0.Maximum_Capacity = (-1915801992);
      airlinetickets0.run();
      airlinetickets0.go(" Seats !!!");
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Airlinetickets.Num_Of_Seats_Sold = (-1862);
      Airlinetickets airlinetickets0 = new Airlinetickets("V';`W", "");
      airlinetickets0.go("s");
      airlinetickets0.checkResult("sxO&&p|", "");
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Airlinetickets airlinetickets0 = null;
      try {
        airlinetickets0 = new Airlinetickets("little", "little");
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      String[] stringArray0 = new String[2];
      // Undeclared exception!
      try { 
        Airlinetickets.main(stringArray0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Airlinetickets airlinetickets0 = new Airlinetickets("lot", "lot");
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Airlinetickets airlinetickets0 = null;
      try {
        airlinetickets0 = new Airlinetickets("average", "average");
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }
}
